### ISSUE TITLE
Video upload to OKFN Labs on YouTube

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator-web#26]
How can I upload (or transfer) videos to the OKFN Labs account on youtube?

I have two videos on my own account:
- https://www.youtube.com/watch?v=f1bTx6Zaotk
- https://www.youtube.com/watch?v=hblUuIjobrc&feature=youtube_gdata

**Comment by trickvi** [comment]
Trying to find the OKFN Labs account (which I didn't even know existed).

**Comment by pwalsh** [comment]
;)

**Comment by pwalsh** [comment]
Note from Rufus is that it should go to Open Knowledge account

**Comment by pwalsh** [comment]
:)

**Comment by pwalsh** [comment]
Anything happening here?

**Comment by pwalsh** [comment]
I'm going to close this one.
