### ISSUE TITLE
Issues with form after submitting and then using the back button

### ISSUE THREAD

**Issue by morty** [okfn/tabular-validator-web#30]
![goodtables](https://cloud.githubusercontent.com/assets/3272/6668855/965036d4-cbed-11e4-94db-009d3f13b6e5.png)

As you can see the File radio button is selected, but it hasn't got the browse button.

Also "Add a data schema" is selected, but the UI to select a schema is not showing. If you unselect and reselect it does show up. If you had previously selected a file, it is showing the same issue as above, that it is missing the browse button.

**Comment by morty** [comment]
In case you need it for debugging these issues were seen with Firefox 36.0.1 on Ubuntu Linux.

**Comment by pwalsh** [comment]
Thanks @morty, this is a great catch, and should be an easy fix.

**Comment by pwalsh** [comment]
Had another bug report for this. Working on it now.
