### ISSUE TITLE
Doesn't cope with quoting in CSV header row

### ISSUE THREAD

**Issue by morty** [okfn/tabular-validator-web#31]
![goodtables2](https://cloud.githubusercontent.com/assets/3272/6671308/54fb45ac-cbfc-11e4-8552-fafd0e06dc84.png)

Data:

``` csv
"Name","Age"
Homer,36
Marge,34
Bart,10
Lisa,8
```

Schema:

``` json
{"fields": [{"name": "Name"}, {"name": "Age"}]}
```

**Comment by pwalsh** [comment]
Nice one. Thanks for the report ;).

**Comment by pwalsh** [comment]
Fixed in https://github.com/okfn/goodtables/commit/e61fa4c519c5877b55f93cef0abf56c70b09b9b8

**Comment by davidread** [comment]
@pwalsh have you considered using the csv parser that comes with python, rather than rolling your own?

**Comment by pwalsh** [comment]
@davidread I haven't rolled my own CSV parser. Have you looked at the code, or just this commit?

I do concede that I should also use the CSV parser for headers.

**Comment by davidread** [comment]
Sounds a good plan
