### ISSUE TITLE
Internal server error if wrong schema is provided

### ISSUE THREAD

**Issue by amercader** [okfn/tabular-validator-web#32]
I added a [link](https://raw.githubusercontent.com/amercader/car-fuel-and-emissions/master/datapackage.json) to a [Data Package](http://dataprotocols.org/data-packages/) schema rather than a [Table one](http://dataprotocols.org/json-table-schema/), and the app crashed with an internal server error.

**Comment by pwalsh** [comment]
Great, thanks for the report @amercader

**Comment by TacoSandwich** [comment]
Also crashes with same error if you nominate a different file type than the one you add, i.e. add a CSV file but tell Goodtables it's actually an XLS file = Crash

**Comment by pwalsh** [comment]
Hi @TacoSandwich thanks. It is a known issue and will be next bug addressed.
