### ISSUE TITLE
Notify when validation job is complete

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator-web#4]
On implementing #3, we will need a way to let a user know that a job is complete. 

This can be done by:
- API endpoint to query
- email

**Comment by rossjones** [comment]
For integration into things like CKAN, posting a response to a URL would be very useful (and reduce the amount of code required on the CKAN side). Just a thought, when providing the url to call back to, would it be possible to have the caller provide some form of cookie/token?  Having an open callable url that changes state in CKAN without being able to restrict it is something that'd need to be avoided.

**Comment by pwalsh** [comment]
Hi @rossjones 

Just a thought: wouldn't it be better, in the case of CKAN, to write an extension using the goodtables Python library (https://github.com/okfn/goodtables)?

**Comment by rossjones** [comment]
Possibly, but it then means CKAN is responsible for running another process that knows how to validate resources - there's no way that doing validation in-line with a request will be a workable solution (it'll just increase the number of timeouts*).  Whilst goodtables exists as a service that people can install themselves, it seems better to just keep the CKAN component small and focused on submitting data.
- It's two http requests (one to GT, one from GT to the datafile) and the processing time of validation.

**Comment by pwalsh** [comment]
Ok gotcha. In the current alpha version of Good Tables everything happens in the request cycle anyway. This issue is a placeholder for some job-based implementation, but it is not a priority _yet_.

cc @rgrp @tryggvib

**Comment by pwalsh** [comment]
Will be done in https://github.com/frictionlessdata/goodtables.io
