### ISSUE TITLE
"Oops. There is no report data to display" when cookies not accepted

### ISSUE THREAD

**Issue by davidread** [okfn/tabular-validator-web#41]
I got this error. I was trying this pair:
- https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/397571/dwp-senior-post-data-sep-2014.csv
- https://github.com/datagovuk/schemas/raw/master/organogram/organogram-senior-staff-csv-schema.json

using: http://goodtables.okfnlabs.org/

**Comment by pwalsh** [comment]
Hi @davidread 

A few things:
1. I'm actually getting a `PipelineBuildError` using those links. Please try that again and confirm.
2. The reason for a pipeline build error is likely that the schema is not a valid [JSON Table Schema](http://dataprotocols.org/json-table-schema/). For example, I can see that you are declaring types incorrectly - they are keywords, not urls to an XML schema definition. [Here is an example schema I made](https://github.com/okfn/goodtables/blob/master/examples/hmt/spend-publishing-schema.json) out of the [Guidance for publishing spend over 25k](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/198197/Guidance_for_publishing_spend_over__25k.pdf) document.

**Comment by pwalsh** [comment]
Also note: which fields are in the `constraints` object, and which are adjacent to it.

**Comment by pwalsh** [comment]
And lastly, if it makes it easier for you in testing, note that Good Tables supports `GET` params. So, rather than filling out the form, you can also use this URL which generates the report for the data and schema you've provided above:

http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json

**Comment by davidread** [comment]
@pwalsh thanks for all of that.

The "Oops" error is repeatable. In Firefox I used the 'copy as curl' command so you can repeat it exactly:

```
curl 'http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json' -H 'Host: goodtables.okfnlabs.org' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'DNT: 1' -H 'Referer: http://goodtables.okfnlabs.org/' -H 'Connection: keep-alive' -H 'Content-Type: multipart/form-data; boundary=---------------------------1766738764322019479522593113' --data-binary $'-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="csrf_token"\r\n\r\n1431447338##796e6d6d0c45df6af3dec20828d28daa1c29c9f2\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="data-field"\r\n\r\noption1\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="data_url"\r\n\r\nhttps://www.gov.uk/government/uploads/system/uploads/attachment_data/file/397571/dwp-senior-post-data-sep-2014.csv\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="data_file"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="format"\r\n\r\ncsv\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="encoding"\r\n\r\n\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="schema-field"\r\n\r\noption1\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="schema_url"\r\n\r\nhttps://github.com/datagovuk/schemas/raw/master/organogram/organogram-senior-staff-csv-schema.json\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="schema_file"; filename=""\r\nContent-Type: application/octet-stream\r\n\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="schema_eg"\r\n\r\n\r\n-----------------------------1766738764322019479522593113\r\n\r\nContent-Disposition: form-data; name="form_action"\r\n\r\n\r\n---------------------------1766738764322019479522593113--\r\n'
```

I get the pipeline error if I do the GET request, rather than the POST.

I'll try and sort my schema out. I see I missed some commas out, so it wouldn't parse as JSON. It would be helpful if you could show errors such as this.

**Comment by davidread** [comment]
I've updated my schema now and although I still get the "Oops" error, with the GET I get some good validation results now.

I'll leave this issue open to help you investigate the "Oops" error.

**Comment by pwalsh** [comment]
Great, thanks David. I'll check it out in the coming days.

**Comment by rufuspollock** [comment]
@pwalsh any update here? I can get this also with e.g. 

http://goodtables.okfnlabs.org/reports?data_url=https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/299476/December_2013__25k_Transparency_Data.csv&format=CSV&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json

**Comment by pwalsh** [comment]
@rgrp @davidread I'm aware of it but have been tied up in other work. The fix is likely something really trivial  - I'll try to look tomorrow.

**Comment by pwalsh** [comment]
@rgrp: Your issue is different - it is a file that chardet fails to detect encoding correctly on. If you change the URL to this it works (Note I pass in a Windows encoding type): http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=ISO-8859-2&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json

Obviously, the error message does nothing whatsoever to help you know that :).

**Comment by pwalsh** [comment]
@davidread are you after a programmatic interface, or the web interface (asking because `curl` came into the picture).

Let's try both:

### API requests

Works for me with `GET` and `POST`.

#### as POST

```
curl http://goodtables.okfnlabs.org/api/run --data "data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystemttachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json"
```

#### as GET

```
curl "http://goodtables.okfnlabs.org/api/run?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystemttachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json"
```

### Web UI Requests

#### as GET

##### via browser

Paste into any browser. This works.

```
http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json
```

##### via curl

This works.

```
curl "http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystemads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json"
```

#### as POST

##### via browser

I can't paste code for that here, but it works using the URLs for data and schema that we are using in all the other examples.

##### via curl

This fails because it has no CSRF token. Is there really a use case for this? I can disable CSRF tokens if you really think there is.

```
curl http://goodtables.okfnlabs.org/reports --data "data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json"
```

**Comment by pwalsh** [comment]
And, specifically about error messages, I've added an item to the backlog for it here https://github.com/okfn/goodtables-web/issues/44

**Comment by davidread** [comment]
@pwalsh I have no need for curl, but I wanted to help you reproduce the issue I see in my browser. Clearly CSRF token doesn't help this testing.

As it stands, I still can't use Good Tables in the normal way, using my browser. I appreciate you've suggested these other ways I can still use the service, and they do work for me, but I imagine I'm not the only person who will be seeing this particular 'Oops' error and think that good tables web site is simply broken. It seems to be something to do with the redirect or maybe you use cookies or HTML5 storage that I've disabled or something like that. If you can't reproduce on your machine it then maybe you could get more people to try it.

**Comment by pwalsh** [comment]
@davidread is there any way you can do a short screencast of this not working in your browser? Also, could you provide additional info on OS/Browser.

**Comment by davidread** [comment]
OSX & Firefox 38.0.1 with a bunch of privacy add-ons.
Start:
![good-1](https://cloud.githubusercontent.com/assets/307612/7910815/bd06ffd0-084f-11e5-8eca-943a294cd023.png)
Hit submit and I get:
![good-2](https://cloud.githubusercontent.com/assets/307612/7910820/c4694210-084f-11e5-9370-7c635502cfc5.png)
If I reload and resubmit the POST, then I get the same result. If I click in the address bar and press enter and do a GET then it does actually work (it shows the validation errors). It also works on my machine from Chrome.

**Comment by pwalsh** [comment]
@davidread thanks for that. I'll check it further. I do have a function that manipulates the form action when the schema or data is a URL, but it should not cause this behaviour as far as I can see. I'll keep this open and have a deeper look.

**Comment by rufuspollock** [comment]
@pwalsh did you get any further on this - do we think this relates to #45

**Comment by pwalsh** [comment]
Didn't check further, and I'm quite convinced that it is/was something very specific with David's Firefox extensions. Of course, it doesn't mean it should not be fixed if we can ascertain the source of the issue, but it does seem a quite obscure thing to hunt down right now. I am certain this is not related to #45.

**Comment by davidread** [comment]
I did a bit more play with this and found that it is due to not my browser not configured to accept cookies by default. Big commercial sites and standard CMSs do detect this sort of thing and give a warning. I guess it's not high on your priorities to do this for a niche site like this.

**Comment by pwalsh** [comment]
@davidread actually, no, if that is the issue, then it is great to identify, and we'd definitely like to add a message to the user that they must have cookies enabled for GoodTables to work.

**Comment by davidread** [comment]
Great, cheers @pwalsh

**Comment by pwalsh** [comment]
FIXED/
