### ISSUE TITLE
Invalid row percentage is off

### ISSUE THREAD

**Issue by trickvi** [okfn/tabular-validator-web#42]
http://goodtables.okfnlabs.org/reports?data_url=https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/299480/December_2013_GPC_Transparency_Data.csv&format=CSV&encoding=&schema_url=https://raw.githubusercontent.com/okfn/tabular-validator/master/examples/hmt/spend-publishing-schema.json

> ## Oops. the data source is not valid.
> 
> "We processed a total of 26 rows, of which 0% were found to have invalid data. Let's have a look at the details." 

There something wrong with the calculation there.

**Comment by pwalsh** [comment]
hmm. it is because the errors are in the header, and not in a "row", as such.

**Comment by pwalsh** [comment]
fixed with #43.
