### ISSUE TITLE
UX improvements - May 2015

### ISSUE THREAD

**Issue by rufuspollock** [okfn/tabular-validator-web#43]
### Results Page
- [x] Show the URL of the data file and the schema file somewhere prominent and easily copyable - why: i may have got to this page by sharing and not know the source files
- [x] link datapipes link for data file so people can view it (or maybe even iframe in but hide - and have preview button next to data file link)
- [ ] preview of json schema (inline into a textarea on the page) - this allows people to understand how it works

Posted a detailed annotated image of the results page image at: https://www.marqueed.com/collections/176586/images/827337/

![good-tables-ux](https://cloud.githubusercontent.com/assets/180658/7837895/d8c1fb34-0481-11e5-998e-fb91918b83eb.png)

**Comment by pwalsh** [comment]
@rgrp thanks. this is tightly related to issue #42. Most of the UX issues you've noted stem from the fact that these errors all come out of the header, and not a "data row" as such, and the post-processing I do on the raw result set when I group for display in a table.

**Comment by pwalsh** [comment]
For reference, here is a better example, as it shows that the result set presentation is generally fine, _except_ in the case of errors in headers:

http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json

**Comment by rufuspollock** [comment]
@pwalsh thanks - also added two new items here re showing links to data and schema files.

Re your comment: I thought we discussed trying to have error messages in the column they related to and having them below the preview row. Not a priority right now relative to maybe some other stuff but something worth considering. (It would be interesting to do some guerilla user testing here and see how people find it ...)

**Comment by pwalsh** [comment]
@rgrp there was definitely talk about messages in columns at some point, but there are some difficult UX issues there. In the current design, there is background highlighting on cells when we know it is a cell error, but this is not working all the time, because some errors are labeled as row errors. There is def. some UX work (and related changes in error data structures) we could do to take this from great to amazing when we get to do another round on it.

**Comment by pwalsh** [comment]
I've done a UX pass. Example:

http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F397571%2Fdwp-senior-post-data-sep-2014.csv&format=csv&encoding=&schema_url=https%3A%2F%2Fgithub.com%2Fdatagovuk%2Fschemas%2Fraw%2Fmaster%2Forganogram%2Forganogram-senior-staff-csv-schema.json

I addressed all issues in the marqueed image, albeit some are in a different manner. Also, I didn't add a preview of the JSON schema, but instead provided a link to it, similar to the data pipes link.

**Comment by rufuspollock** [comment]
FIXED. New items in a separate issue.
