### ISSUE TITLE
Using GET not POST on file submissions (and getting rid of JS url rewriting)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/tabular-validator-web#45]
Is this done already? If not could we prioritize it - i think it may fix other bugs we have ...

/cc @pwalsh

**Comment by pwalsh** [comment]
Really not convinced that this is required: bug in #41 seems quite subtle and specific to FF + extensions.

Also, this only considers the cases with URLs - we still need to handle file uploads / `multipart/form-data`

**Comment by rufuspollock** [comment]
I thought idea is we only use GET request is both data and schema are non-upload (which is common) and o/w remains POST (so we have some JS in this app). (Alternatively we redirect in the backend from POST to GET).

I still get bugginess - i think - using back button ... (but may be wrong).

**Comment by pwalsh** [comment]
hmmm. I fixed bugginess, based on the previous js trick I was doing on the report page. lemme check all these scenarios on thursday and we'll see.

**Comment by rufuspollock** [comment]
@pwalsh what happened here? If nothing no problem but wondered if a follow up.

**Comment by pwalsh** [comment]
Nothing happened here. I'm not convinced there is a problem to solve. 

But, in terms of where I'd like to see the GoodTables web service go, see [comments here](https://github.com/okfn/goodtables-web/issues/46). Clean separation of API and UI would simplify stuff like this IMHO (eg: I wouldn't rely on server side forms and all the "classic" handling of submitted data).

**Comment by pwalsh** [comment]
WONTFIX. There is nothing here to fix, and #41 is solved.
