### ISSUE TITLE
event loop for /api/run

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator-web#46]
It is currently blocking. We can do something nice with Py3 and for example https://github.com/KeepSafe/aiohttp

**Comment by rufuspollock** [comment]
Or we could use node ;-)

**Comment by pwalsh** [comment]
Well, you know I have no problem with Node :). 

But in this case, where the codebase is already in Python, and, with where Python 3 has got to with `asyncio` and `concurrent.futures`, I think that implementing in this in Python will be quite straight forward, with a huge gain in performance/scalability of this endpoint.

Related, I actually think we should just get rid of Flask for the GoodTables web server, have an async API for validation, and have the web UI be a client side app that uses the API. We've already got quite a lot of the tooling for this in DataPackagist, including for example, the templates for displaying GoodTables results.

**Comment by rufuspollock** [comment]
Isn't DataPackagist node only?

**Comment by pwalsh** [comment]
All libs in DataPackagist run client or server. For the stuff I refer to here - it is just a bunch of templates in backbone, and libs like our JS client for the GoodTables web service.

**Comment by pwalsh** [comment]
Will be dealt with in https://github.com/frictionlessdata/goodtables.io
