### ISSUE TITLE
Example bad CSV files (with quick link on main page to use them)

### ISSUE THREAD

**Issue by rufuspollock** [okfn/tabular-validator-web#48]
- On form have "(Example CSV 1, Example CSV 2)
- 2 csvs in this repo showing various bad features
  - one just bad structurally
  - one is bad against the schema

**Comment by danfowler** [comment]
Added by f17a21c6354cac8942ff94bae637fb7d298cd259

**Comment by rufuspollock** [comment]
- [ ] Split out onto separate line in help
- [ ] "Want to see an example? Example: invalid structure. Example: invalid schema.
- [ ] invalid schema should also set schema
- [ ] Can we just make these a bit more exciting. (optional for now)

**Comment by rufuspollock** [comment]
@danfowler how are we here?

I think we really do want better examples for demoing. E.g.
- Structure:
  - Can I have the column somewhere more prominent
  - Can I also have a bad row of some kind e.g. entirely blank plus one row with more values than the header row
- Schema
  - I want to see some type errors as well as the headers being wrong
  - We _really_ need to sort out the header display UX - right now it really does not work (but that's another issue ;-) ...)

**Comment by danfowler** [comment]
Re: Structure: I can make the "invalid structure" changes, although I'm having trouble triggering any error on an entirely blank row, either on the web interface or via the CLI.

![screen shot 2015-08-28 at 11 13 47](https://cloud.githubusercontent.com/assets/772616/9542013/e7b3a0a6-4d75-11e5-837f-9a2d54c0f8f0.png)

**Comment by danfowler** [comment]
Re: Schema: I can make this happen:

![screen shot 2015-08-28 at 11 21 25](https://cloud.githubusercontent.com/assets/772616/9542151/faa58aa2-4d76-11e5-9f20-879f2dbf8074.png)

**Comment by rufuspollock** [comment]
Re schema: This is _much_ better - please let's do this :-)

Re structure: that would seem to be a bug - though to check is this an empty row in the middle of a bunch of rows or at the end. If you can't get it to trigger this sounds like a bug and i would open a separate issue and try to check the tests in the base library.

**Comment by danfowler** [comment]
This was done :)
