### ISSUE TITLE
UX improvements July 2015

### ISSUE THREAD

**Issue by rufuspollock** [okfn/tabular-validator-web#50]
Primarily item 11 in https://www.marqueed.com/collections/176586/images/827337/
- [ ] data file link
- [ ] json schema link
- [ ] results as json link
- [ ] data file preview

**Comment by rufuspollock** [comment]
@danfowler where are we with this? Do you feel it is done? Should we do a short review together?

**Comment by danfowler** [comment]
Yes, that would be helpful.

**Comment by georgiana-b** [comment]
This seems solved to me. Is anyone unhappy with the way they work/look now?

**Comment by pwalsh** [comment]
FIXED. Can add specific issues if still required
