### ISSUE TITLE
Provide option in UI to validate more than 20,000 rows

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/tabular-validator-web#54]
We have some large datasets to publish. We validate them using the GoodTables user interface or CSVLint before publishing. For big CSV files (>20,000 rows) we can't use GoodTables.

This feature request would allow users to manually override the 20,000 row limit (with an appropriate warning and upper limit).

**Comment by pwalsh** [comment]
@Stephen-Gates for your data, what would be a good upper limit that would not restrict you in any way? 100,000 rows? More?

**Comment by pwalsh** [comment]
And just to be clear, this issue is about exposing the option via the UI, as the API itself already supports the option.

**Comment by Stephen-Gates** [comment]
@pwalsh yes it is about exposing the option via the UI. 
The data publishing team has left for the day. An answer for you tomorrow.

**Comment by Stephen-Gates** [comment]
@pwalsh. Two biggest datasets I found:
- [Vehicle registration](https://data.qld.gov.au/dataset/crash-data-from-queensland-roads/resource/e88943c0-5968-4972-a15f-38e120d72ec0) - 23Mb zipped
- [Road Crash](https://data.qld.gov.au/dataset/crash-data-from-queensland-roads/resource/e88943c0-5968-4972-a15f-38e120d72ec0) - 115Mb = 251706 rows

**Comment by Stephen-Gates** [comment]
@pwalsh 100,000 row will address 99% of our requirements. Two datasets above are outliers re: size.

**Comment by pwalsh** [comment]
@Stephen-Gates ok great thanks.

**Comment by pwalsh** [comment]
FIXED.
