### ISSUE TITLE
API for bulk submissions

### ISSUE THREAD

**Issue by pwalsh** [okfn/tabular-validator-web#6]
Bulk submit of data sources, or data packages

**Comment by pmackay** [comment]
+1 - handling data packages would be great. Any upcoming plans for this?

**Comment by pwalsh** [comment]
Hi @pmackay 

There are no immediate plans for this via API, although we'd like to do it.

For now, if you use the Good Tables library in Python, you can run a batch pipeline on a CSV which contains rows of sources, or a `datapackage.json`:

https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/batch.py

As well as the docstring, there are some (light) docs for it here, and a link to another library that uses the batch pipeline: http://goodtables.readthedocs.org/en/latest/batch.html

I hope that can help you for now.

**Comment by pwalsh** [comment]
Will be done in https://github.com/frictionlessdata/goodtables.io in general.

Specifically, @pmackay we now support datapackage on the `next` branch at https://github.com/frictionlessdata/goodtables-py/tree/next (will be merged to master and pushed to pipit in days)
