### ISSUE TITLE
Open Knowledge International pull-down tab shifted over to left

### ISSUE THREAD

**Issue by danfowler** [okfn/tabular-validator-web#63]
<img width="287" alt="screen shot 2016-07-18 at 16 15 47" src="https://cloud.githubusercontent.com/assets/772616/16929171/8163ad2a-4d04-11e6-8c43-0ee0a18141f3.png">

Using Chrome Version 51.0.2704.106 (64-bit) on Mac OS X

**Comment by roll** [comment]
the same for me

**Comment by danfowler** [comment]
Issue is update to newer CSS: https://github.com/frictionlessdata/goodtables-web/blob/9450beef15998c7e7c2b058c4267bc22676e6cd2/web/theme/templates/base.html

**Comment by pwalsh** [comment]
this is probably some conflict between the css here, as Dan notes, and the changes we made to the pull down when we ported it to a.okfn.org, and possibly something in the code there when I removed jQuery as a dependency.

**Comment by rufuspollock** [comment]
@pwalsh i think this may be quite a major bug as it prevents one clicking on any part of the menu bar:

> @roll @pwalsh when i go do http://goodtables.okfnlabs.org/ i can’t click on any of the top navbar - is that just me?

**Comment by rufuspollock** [comment]
OK, i've tracked this down to the OKI panel being set to absolute. I've changed this to relative following https://a.okfn.org/html/oki/panel/.

However, there  were still issues in that ribbon would not be on same line as menu (it would be above it). It seems that location of panel is not just coming from the panel css on https://a.okfn.org/html/oki/panel/ but also from some stuff in the app-theme:

https://cdn.rawgit.com/okfn/app-theme/v2.1.0/css/sass/_theme.scss

Next step is to try to port those fixes over

**Comment by rufuspollock** [comment]
Aside: all the assets and scss stuff seems to be commented out in `web/factory.py` - thus i assume scss is not getting built ...

**Comment by rufuspollock** [comment]
It looks to me that this change is the relevant commit: https://github.com/okfn/app-theme/commit/26e317f751db1fa3ee9fc6f8768c3ab459103d63

**Comment by rufuspollock** [comment]
Solution: port the change to local sass.

**Comment by danfowler** [comment]
Thanks @rufuspollock 

Deployed changes: http://goodtables.okfnlabs.org/
