### ISSUE TITLE
Duplicate testing - is Primary key considered?

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/tabular-validator-web#64]
I have a dataset [republished at datahub.io](https://datahub.io/dataset/cffe2704-d335-41d9-b6b7-014f2bde5339/resource/85555249-4d1d-4158-8bf5-642e6d54b0e0/download/averagebicyclecountsbydayandhour.csv). It has four fields that make up the primary key. These are not the first four fields in the table. When I test in GoodTables: 
- it detects duplicates (a fair enough guess)
- it correctly ignores duplicates when I choose that option in the user interface 
- it detects duplicates when I use a json table schema without a primary key
- it [correctly ignores duplicates](http://goodtables.okfnlabs.org/reports?report_limit=1000&row_limit=100000&report_type=grouped&format=csv&schema=%7B%0A++%22fields%22%3A+%5B%0A++++%7B%0A++++++%22name%22%3A+%22SITE_ID%22%2C%0A++++++%22description%22%3A+%22ID+number+of+each+site+collecting+data%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22required%22%3A+true%2C%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22DESCRIPTION%22%2C%0A++++++%22description%22%3A+%22Site+description%22%2C%0A++++++%22type%22%3A+%22string%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22required%22%3A+true%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22MONTHS%22%2C%0A++++++%22description%22%3A+%22Month+data+was+collected+in+e.g.+January%22%2C%0A++++++%22type%22%3A+%22string%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22required%22%3A+true%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22YEARS%22%2C%0A++++++%22description%22%3A+%22Year+data+was+collected+in+e.g.+2016%22%2C%0A++++++%22type%22%3A+%22date%22%2C%0A++++++%22format%22%3A+%22fmt%3A%25Y%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22required%22%3A+true%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22HOURS%22%2C%0A++++++%22description%22%3A+%22Hour+data+was+collected+in+e.g.+0..23%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22required%22%3A+true%2C%0A++++++++%22minimum%22%3A+0%2C%0A++++++++%22maximum%22%3A+23%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22SATURDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time.+Can+be+null+if+there+is+a+error+recording+data.%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22SUNDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22MONDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22TUESDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22WEDNESDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22THURSDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%2C%0A++++%7B%0A++++++%22name%22%3A+%22FRIDAY%22%2C%0A++++++%22description%22%3A+%22Average+amount+of+bicycle+counts+that+was+recorded+on+this+day+and+time%22%2C%0A++++++%22type%22%3A+%22integer%22%2C%0A++++++%22constraints%22%3A+%7B%0A++++++++%22minimum%22%3A+0%0A++++++%7D%0A++++%7D%0A++%5D%2C%0A++%22primaryKey%22%3A+%5B%0A++++%22SITE_ID%22%2C%0A++++%22MONTHS%22%2C%0A++++%22YEARS%22%2C%0A++++%22HOURS%22%0A++%5D%0A%7D&data=https%3A%2F%2Fdatahub.io%2Fdataset%2Fcffe2704-d335-41d9-b6b7-014f2bde5339%2Fresource%2F85555249-4d1d-4158-8bf5-642e6d54b0e0%2Fdownload%2Faveragebicyclecountsbydayandhour.csv&ignore_duplicate_rows=True) when I use a json table schema with a primary key and choose the ignore duplicates option in the user interface
- it **incorrectly detects duplicates** when I use a json table schema with a primary key
  
   `"primaryKey": ["SITE_ID",  "MONTHS", "YEARS", "HOURS"]`

Is the primary key in the schema considered when checking for duplicates?

**Comment by roll** [comment]
Please use https://try.goodtables.io
