### ISSUE TITLE
Support the use of data packages for data validation

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/tabular-validator-web#65]
[Data Packagist](http://datapackagist.okfnlabs.org) helps you build a data package for your data and a schema for your resources. Then to validate your data in Good Tables, you must supply a json table schema, so you have to cut the schema out from the data package you've created. This is an extra step that is not needed.

Consider allowing the user to define a data package to use for validation in Good Tables. If the package has multiple resources, let the user pick the appropriate one.

**Comment by roll** [comment]
Please use https://try.goodtables.io
