### ISSUE TITLE
Let the user set an upper limit for number of errors reported

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/tabular-validator-web#66]
After creating my JSON Table Schema I want to test the types, formats and constraints work as expected. To do this I take my data and create a number of test cases for each field. These can't be all tested in one go as Good Tables appears to stop at some point saying, 

`Below we have a sample of 10 errors found when validating the data. Use this to identify problems, fix them in the source, and then upload the data to validate again!`

As a suggestion, allow the user to set an upper limit for the number of errors reported.

**Comment by roll** [comment]
Please use https://try.goodtables.io
