### ISSUE TITLE
State what tests aren't performed on home page

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/tabular-validator-web#69]
Add a note to describe the tests not performed against a supplied schema. E.g. 

At present Good Tables does not test [foreign keys](https://github.com/frictionlessdata/goodtables/issues/8), data type formats or [some constraints](https://github.com/frictionlessdata/goodtables/issues/55).

By stating what isn't checked, users will know what bad data may slip through despite their awesome schema.

**Comment by roll** [comment]
Please use https://try.goodtables.io
