### ISSUE TITLE
Invalid CSV file error reports (wrongly) as csv being html

### ISSUE THREAD

**Issue by rufuspollock** [okfn/tabular-validator-web#73]
http://goodtables.okfnlabs.org/reports?data_url=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Fdataportals.org%2Fmaster%2Fdata%2Fportals.csv&format=csv&encoding=&schema_url=

![image](https://cloud.githubusercontent.com/assets/180658/24329235/40236a08-11f8-11e7-9e33-8fed4e75ecc5.png)

https://raw.githubusercontent.com/okfn/dataportals.org/master/data/portals.csv [note this file may have changed by the time you try this - you want this version https://github.com/okfn/dataportals.org/blob/51538503f15bdb021763af448cdda336de8d312a/data/portals.csv]

**Comment by roll** [comment]
Please use https://try.goodtables.io
