### ISSUE TITLE
Add support for different separator values

### ISSUE THREAD

**Issue by schlos** [okfn/tabular-validator-web#75]
**Current:**
Goodtables supports only CSV with comma separator (delimiter).

**Expected:**
Please support selection of value separator:
- semicolon
- comma
- tab

**CSV specification**
https://en.wikipedia.org/wiki/Comma-separated_values#Specification

RFC 4180 proposes a specification for the CSV format, and this is the definition commonly used. However, in popular usage "CSV" is not a single, well-defined format. As a result, in practice the term "CSV" might refer to any file that:

- is plain text using a character set such as ASCII, various Unicode character sets (e.g. UTF-8), EBCDIC, or Shift JIS,
- consists of records (typically one record per line),
- with the records divided into fields separated by delimiters (typically a single reserved character such as **comma, semicolon, or tab**; sometimes the delimiter may include optional spaces),
where every record has the same sequence of fields.

**Comment by roll** [comment]
@schlos 
Thanks for your feedback!

May be you'll be interested - https://discuss.okfn.org/t/launching-goodtables-io-tell-us-what-you-think/5165

**Comment by roll** [comment]
Please use https://try.goodtables.io
