### ISSUE TITLE
Excel format not working

### ISSUE THREAD

**Issue by gustavodemari** [okfn/tabular-validator-web#76]
I tried to validate many Excel files and none was working.

URL example that I tried.

https://github.com/chiphuyen/tf-stanford-tutorials/blob/master/data/fire_theft.xls

Response:

http://datapipes.okfnlabs.org/csv/head%C2%A0-n%C2%A01000/html?url=https://github.com/chiphuyen/tf-stanford-tutorials/blob/master/data/fire_theft.xls

**Comment by pwalsh** [comment]
@gustavodemari 

Can you provide some other example Excel files that you have tried and do not work? The one you provided is also considered invalid by my desktop spreadsheet software (Apple Numbers)

**Comment by roll** [comment]
Please use https://try.goodtables.io
