### ISSUE TITLE
missing values in schema

### ISSUE THREAD

**Issue by Tweety79rw** [okfn/tabular-validator-web#78]
# Problem
The web API doesn't seam to be using the missing values in the schema compared to goodtables.io or goodtables.exe with the same data.

# Possible solution
Does the goodtables web just need to be updated with the latest goodtables-py

# Resources used
Data url: https://raw.githubusercontent.com/PNNL-Comp-Mass-Spec/MetabolomicsCCS/master/data/metabolitedata.tsv

Schema url: https://raw.githubusercontent.com/PNNL-Comp-Mass-Spec/MetabolomicsCCS/master/metabolitedata-schema.json

**Comment by danfowler** [comment]
@Tweety79rw hi, you are correct in identifying that the current `goodtables-web` codebase still uses the old version of the goodtables Python library and pre-`missingValues` Frictionless Data specs.  There is ongoing discussion on how best to create a new app that fulfills the function of the old `goodtables-web`.

**Comment by pwalsh** [comment]
@Tweety79rw @danfowler it is actually not too far away, we are targeting this to be beta testable next week (functionally solid, UI sketchy)

**Comment by roll** [comment]
Please use https://try.goodtables.io
