### ISSUE TITLE
Trouble analyzing excel files

### ISSUE THREAD

**Issue by sjb287** [okfn/tabular-validator-web#79]
I tried validating some excel tables as a test case taken from the supplementary information of this paper:
https://onlinelibrary.wiley.com/doi/full/10.1111/j.1365-313X.2012.05033.x

Using the following URLs did not work:
https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fj.1365-313X.2012.05033.x&attachmentId=79329996
https://onlinelibrary.wiley.com/action/downloadSupplement?doi=10.1111%2Fj.1365-313X.2012.05033.x&attachmentId=79329997

So I downloaded the files and tried uploading a file, this did not work either, I got the error:
'_io.BytesIO' object has no attribute 'decode'

I might be doing something wrong here.
[tpj_5033_sm_tables2.xlsx](https://github.com/frictionlessdata/goodtables-web/files/1844573/tpj_5033_sm_tables2.xlsx)
[tpj_5033_sm_tables5.xlsx](https://github.com/frictionlessdata/goodtables-web/files/1844574/tpj_5033_sm_tables5.xlsx)

**Comment by roll** [comment]
Please use https://try.goodtables.io
